function optionsPage(){
  const I = this;
  I.wait(10);
  I.selectOption('select[id="next-step"]', 'Amend Application Details');
  I.wait(10);
  I.click('Go');
  I.wait(10);
  I.fillField('input[id="solicitorPhone"]', '07766120000');
  I.wait(5);
  I.click('Continue');
  I.wait(10);
  I.fillField('input[id="divorceCaseNumber"]', 'EM18D84321');
  I.wait(5);
  I.click('Continue');
  I.wait(10);
  I.click('Continue');
  I.wait(10);
  I.fillField('input[id="rSolicitorEmail"]', 'mahsol@mailinator.com');
  I.wait(5);
  I.click('Continue');
  I.wait(10);
  I.checkOption('input[value="Property Adjustment  Order"]');
  I.wait(5);
  I.click('Continue');
  I.wait(10);
  I.checkOption('input[id="orderForChildrenQuestion1-No"]');
  I.wait(5);
  I.click('Continue');
  I.wait(10);
  I.click('Continue');
  I.wait(10);
  I.checkOption('input[id="d81Question-No"]');
  I.wait(5);
  I.attachFile('input[id="d81Applicant"]', 'data/fileupload.txt');
  I.wait(5);
  I.attachFile('input[id="d81Respondent"]', 'data/fileupload.txt');
  I.wait(5);
  I.click('Continue');
  I.wait(10);
  I.click('Continue');
  I.wait(10);
  I.click('Continue');
  I.wait(10);
  I.see('SOLICITOR DETAILS');
  I.see('DIVORCE DETAILS');
  I.see('APPLICANT DETAILS');
  I.see('RESPONDENT DETAILS');
  I.wait(10);
  I.click('Submit');
  I.wait(10);
  I.see('Amend Application Details');
  I.wait(10);
  I.selectOption('select[id="next-step"]', 'Case Submission');
  I.wait(10);
  I.click('Go');
  I.wait(10);
}

module.exports = { optionsPage };