var caseRequest = {
  'data': {
    'isAdmin': 'No',
    'applicantSolicitorName': 'Vivien Henry',
    'applicantSolicitorFirm': 'Tempora sit nisi pr',
    'solicitorReference': '343',
    'applicantSolicitorAddress': {
      'AddressLine1': 'Flat 8',
      'AddressLine2': '1 St. James\'s Street',
      'AddressLine3': '',
      'PostTown': 'London',
      'County': '',
      'PostCode': 'SW1A 1EF',
      'Country': 'United Kingdom'
    },
    'applicantSolicitorPhone': '+1 (332) 676-8024',
    'applicantSolicitorEmail': 'qoqihatu@mailinator.net',
    'applicantSolicitorDXnumber': '24',
    'applicantSolicitorConsentForEmails': 'No',
    'divorceCaseNumber': 'LV18D84321',
    'dateOfMarriage': '2010-12-25',
    'dateOfSepration': '2015-03-21',
    'divorcePetitionIssuedDate': '1996-02-04',
    'nameOfCourtDivorceCentre': 'Alice Pugh',
    'divorceStageReached': 'Decree Absolute',
    'divorceDecreeAbsoluteDate': '2019-09-10',
    'divorceUploadEvidence2': {
      'document_url': 'http://dm-store-aat.service.core-compute-aat.internal:443/documents/5f8ae4fc-23c1-41a8-904f-59a8a88f9187',
      'document_binary_url': 'http://dm-store-aat.service.core-compute-aat.internal:443/documents/5f8ae4fc-23c1-41a8-904f-59a8a88f9187/binary',
      'document_filename': 'dummy.pdf'
    },
    'applicantFMName': 'Paula Ballard',
    'applicantLName': 'Crane',
    'respondentFMName': 'Liberty Thompson',
    'respondentLName': 'Salazar',
    'respondentRepresented': 'Yes',
    'rSolicitorName': 'Mona Stokes',
    'rSolicitorReference': 'Ea dolorum rerum neq',
    'rSolicitorFirm': 'Eaque optio ex sequ',
    'rSolicitorAddress': {
      'AddressLine1': 'Fortitude Uk 72392',
      'AddressLine2': '',
      'AddressLine3': '',
      'PostTown': 'London',
      'County': '',
      'PostCode': 'SW18 9PR',
      'Country': 'United Kingdom'
    },
    'rSolicitorPhone': '+1 (588) 149-5062',
    'rSolicitorEmail': 'sijydu@mailinator.com',
    'rSolicitorDXnumber': '953',
    'natureOfApplicationChecklist': [
      'Maintenance pending suite',
      'propertyAdjustmentOrder',
      'Pension Compensation Attachment Order',
      'Pension Compensation Sharing Order',
      'Pension Attachment Order',
      'Pension Sharing Order',
      'Lump Sum Order',
      'periodicalPaymentOrder'
    ],
    'propertyAddress': 'Dolorum praesentium',
    'mortgageDetail': 'Aut aut voluptate et',
    'additionalPropertyOrderDecision': 'No',
    'paymentForChildrenDecision': 'No',
    'fastTrackDecision': 'Yes',
    'fastTrackDecisionReason': [
      'reason_4',
      'reason_3',
      'reason_2',
      'reason_1'
    ],
    'addToComplexityListOfCourts': 'trueDontKnow',
    'estimatedAssetsChecklist': [
      'estimatedAssetsChecklist_5',
      'estimatedAssetsChecklist_4',
      'estimatedAssetsChecklist_3',
      'estimatedAssetsChecklist_2',
      'estimatedAssetsChecklist_1'
    ],
    'netValueOfHome': '10000000',
    'potentialAllegationChecklist': [
      'notApplicable',
      'potentialAllegationChecklist_14',
      'potentialAllegationChecklist_13',
      'potentialAllegationChecklist_12',
      'potentialAllegationChecklist_11',
      'potentialAllegationChecklist_10',
      'potentialAllegationChecklist_9',
      'potentialAllegationChecklist_8',
      'potentialAllegationChecklist_7',
      'potentialAllegationChecklist_6',
      'potentialAllegationChecklist_5',
      'potentialAllegationChecklist_4',
      'potentialAllegationChecklist_3',
      'potentialAllegationChecklist_2',
      'potentialAllegationChecklist_1'
    ],
    'detailPotentialAllegation': 'something',
    'otherReasonForComplexity': 'No',
    'allocatedCourtList': 'nottingham',
    'nottinghamCourtList': 'FR_s_NottinghamList_8',
    'specialAssistanceRequired': 'none',
    'specificArrangementsRequired': 'none',
    'isApplicantsHomeCourt': 'No',
    'applicantAttendedMIAM': 'No',
    'claimingExemptionMIAM': 'Yes',
    'familyMediatorMIAM': 'No',
    'MIAMExemptionsChecklist': [
      'other',
      'previousMIAMattendance',
      'urgency',
      'domesticViolence'
    ],
    'MIAMDomesticViolenceChecklist': [
      'FR_ms_MIAMDomesticViolenceChecklist_Value_22',
      'FR_ms_MIAMDomesticViolenceChecklist_Value_21',
      'FR_ms_MIAMDomesticViolenceChecklist_Value_20',
      'FR_ms_MIAMDomesticViolenceChecklist_Value_19',
      'FR_ms_MIAMDomesticViolenceChecklist_Value_18',
      'FR_ms_MIAMDomesticViolenceChecklist_Value_17',
      'FR_ms_MIAMDomesticViolenceChecklist_Value_16',
      'FR_ms_MIAMDomesticViolenceChecklist_Value_15',
      'FR_ms_MIAMDomesticViolenceChecklist_Value_13',
      'FR_ms_MIAMDomesticViolenceChecklist_Value_12',
      'FR_ms_MIAMDomesticViolenceChecklist_Value_11',
      'FR_ms_MIAMDomesticViolenceChecklist_Value_10',
      'FR_ms_MIAMDomesticViolenceChecklist_Value_9',
      'FR_ms_MIAMDomesticViolenceChecklist_Value_8',
      'FR_ms_MIAMDomesticViolenceChecklist_Value_7',
      'FR_ms_MIAMDomesticViolenceChecklist_Value_6',
      'FR_ms_MIAMDomesticViolenceChecklist_Value_5',
      'FR_ms_MIAMDomesticViolenceChecklist_Value_4',
      'FR_ms_MIAMDomesticViolenceChecklist_Value_3',
      'FR_ms_MIAMDomesticViolenceChecklist_Value_2',
      'FR_ms_MIAMDomesticViolenceChecklist_Value_1'
    ],
    'MIAMUrgencyReasonChecklist': [
      'FR_ms_MIAMUrgencyReasonChecklist_Value_5',
      'FR_ms_MIAMUrgencyReasonChecklist_Value_4',
      'FR_ms_MIAMUrgencyReasonChecklist_Value_3',
      'FR_ms_MIAMUrgencyReasonChecklist_Value_2',
      'FR_ms_MIAMUrgencyReasonChecklist_Value_1'
    ],
    'MIAMPreviousAttendanceChecklist': 'FR_ms_MIAMPreviousAttendanceChecklist_Value_5',
    'MIAMOtherGroundsChecklist': 'FR_ms_MIAMOtherGroundsChecklist_Value_11',
    'promptForAnyDocument': 'No'
  },
  'event': {
    'id': 'FR_solicitorCreate',
    'summary': '',
    'description': ''
  },
  'event_token': 'eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJxZ3RzbXVqdTVyMWtjY21oMHRuNjcwcnA5NyIsInN1YiI6Ijk2ODM0IiwiaWF0IjoxNTY5MzMzNjA0LCJldmVudC1pZCI6IkZSX3NvbGljaXRvckNyZWF0ZSIsImNhc2UtdHlwZS1pZCI6IkZpbmFuY2lhbFJlbWVkeUNvbnRlc3RlZCIsImp1cmlzZGljdGlvbi1pZCI6IkRJVk9SQ0UiLCJjYXNlLXZlcnNpb24iOiJiZjIxYTllOGZiYzVhMzg0NmZiMDViNGZhMDg1OWUwOTE3YjIyMDJmIn0.njOEoOE4CetwvE0uVOt2hPT4rNb1LXGcZIw3QvOXG8k',
  'ignore_warning': false,
  'draft_id': null
};

exports.default = caseRequest; 