function contestedHwfOptionsPage(){
  const I = this;
  I.wait(10);
  I.selectOption('select[id="next-step"]', 'Amend Application Details');
  I.wait(10);
  I.click('Go');
  I.wait(10);
  I.waitForContinueButtonEnabled();
  I.click('Continue') ;
  I.wait(10);
  I.fillField('input[id="applicantSolicitorPhone"]', '07766121111');
  I.wait(10);
  I.waitForContinueButtonEnabled();
  I.click('Continue') ;
  I.wait(10);
  I.fillField('input[id="divorceCaseNumber"]', 'EM18D33333');
  I.wait(10);
  I.waitForContinueButtonEnabled();
  I.click('Continue') ;
  I.wait(10);
  I.waitForContinueButtonEnabled();
  I.click('Continue') ;
  I.wait(10);
  I.waitForContinueButtonEnabled();
  I.click('Continue') ;
  I.wait(10);
  I.fillField('input[id="rSolicitorEmail"]', 'livamend@mailinator.com');
  I.wait(10);
  I.waitForContinueButtonEnabled();
  I.click('Continue') ;
  I.wait(10);
  I.checkOption('input[id="natureOfApplicationChecklist-propertyAdjustmentOrder"]');
  I.wait(10);
  I.waitForContinueButtonEnabled();
  I.click('Continue') ;
  I.wait(10);
  I.waitForContinueButtonEnabled();
  I.click('Continue') ;
  I.wait(10);
  I.waitForContinueButtonEnabled();
  I.click('Continue') ;
  I.wait(10);
  I.waitForContinueButtonEnabled();
  I.click('Continue') ;
  I.wait(10);
  I.checkOption('input[id="isApplicantsHomeCourt-No"]');
  I.wait(10);
  I.waitForContinueButtonEnabled();
  I.click('Continue') ;
  I.wait(10);
  I.waitForContinueButtonEnabled();
  I.click('Continue') ;
  I.wait(10);
  I.fillField('#soleTraderName', 'sole trading');
  I.wait(10);
  I.waitForContinueButtonEnabled();
  I.click('Continue') ;
  I.wait(10);
  I.waitForContinueButtonEnabled();
  I.click('Continue') ;
  I.wait(10);
  I.waitForContinueButtonEnabled();
  I.click('Continue') ;
  I.wait(10);
  I.see('Solicitor Details');
  I.see('Divorce Details');
  I.see('Applicant’s Details');
  I.see('Respondent’s Details');
  I.see('Is the respondent represented ?');
  I.see('Do you want to upload any other documents ?');
  I.wait(10);
  I.click('Submit');
  I.wait(10);
  I.see('Amend Application Details');
  I.wait(10);
  I.selectOption('select[id="next-step"]', 'Case Submission');
  I.wait(10);
  I.click('Go');
  I.wait(10);
}

module.exports = { contestedHwfOptionsPage };